package main

var EXTENSIONS = map[string]string {
  "asax" : "ASP.NET",
  "ascx" : "ASP.NET",
  "ashx" : "ASP.NET",
  "asmx" : "ASP.NET",
  "axd" : "ASP.NET",

  "as" : "ActionScript",

  "adb" : "Ada",
  "ada" : "Ada",
  "ads" : "Ada",
  
  "go" : "Go",
  "mod" : "Go",
  "sum" : "Go",
  
  "js" : "JavaScript",
  "_js" : "JavaScript",
  "bones" : "JavaScript",
  "cjs" : "JavaScript",
  "es" : "JavaScript",
  "es6" : "JavaScript",
  "frag" : "JavaScript",
  "gs" : "JavaScript",
  "jake" : "JavaScript",
  "javascript" : "JavaScript",
  "jsb" : "JavaScript",
  "jscad" : "JavaScript",
  "jsfl" : "JavaScript",
  "jsm" : "JavaScript",
  "jss" : "JavaScript",
  "jsx" : "JavaScript",
  "mjs" : "JavaScript",
  "njs" : "JavaScript",
  "pac" : "JavaScript",
  "sjs" : "JavaScript",
  "ssjs" : "JavaScript",
  "xsjs" : "JavaScript",
  "xsjslib" : "JavaScript",

  "kt" : "Kotlin",
  "ktm" : "Kotlin",
  "kts" : "Kotlin",

  "md" : "Markdown",

  "py" : "Python",
  "cgi" : "Python",
  "fcgi" : "Python",
  "gyp" : "Python",
  "gypi" : "Python",
  "lmi" : "Python",
  "py3" : "Python",
  "pyde" : "Python",
  "pyi" : "Python",
  "pyp" : "Python",
  "pyt" : "Python",
  "pytb" : "Python",
  "pyw" : "Python",
  "rpy" : "Python",
  "smk" : "Python",
  "spec" : "Python",
  "tac" : "Python",
  "wsgi" : "Python",
  "xpy" : "Python",

  "rs" : "Rust",
  "rs.in" : "Rust",

  "swift" : "Swift",

  "ts" : "TypeScript",
}