package main

// Counter for each language
var LANG = map[string]int64 {
  "ASP.NET" : 0,
  "ActionScript" : 0,
  "Ada" : 0,
  "AppleScript" : 0,
  "AsciiDoc" : 0,
  "Assembly" : 0,
  "Astro" : 0,
  "AutoHotKey" : 0,
  "Awk" : 0,
  "BASIC" : 0,
  "Batchfile" : 0,
  "Beef" : 0,
  "BibTeX" : 0,
  "Bison" : 0,
  "Blade" : 0,
  "BlitzMax" : 0,
  "Bluespec" : 0,
  "Boo" : 0,
  "Boogie" : 0,
  "Brainfuck" : 0,
  "Brightscript" : 0,
  "C" : 0,
  "C#" : 0,
  "C++" : 0,
  "CMake" : 0,
  "COBOL" : 0,
  "CSON" : 0,
  "CSS" : 0,
  "CSV" : 0,
  "CUE" : 0,
  "Ceylon" : 0,
  "Chapel" : 0,
  "Classic ASP" : 0,
  "Clojure" : 0,
  "CodeQL" : 0,
  "CoffeeScript" : 0,
  "Common Lisp" : 0,
  "Common Workflow Language" : 0,
  "Crystal" : 0,
  "Cuda" : 0,
  "Cython" : 0,
  "D" : 0,
  "Dart" : 0,
  "Docker" : 0,
  "Dogescript" : 0,
  "EJS" : 0,
  "Elixir" : 0,
  "Elm" : 0,
  "EmberScript" : 0,
  "Erlang" : 0,
  "F#" : 0,
  "Fortran" : 0,
  "Frege" : 0,
  "Glyph": 0,
  "Go" : 0,
  "Golo" : 0,
  "Gosu" : 0,
  "Gradle" : 0,
  "GraphQL" : 0,
  "Groovy" : 0,
  "HTML" : 0,
  "HTTP" : 0,
  "Haskell" : 0,
  "Java" : 0,
  "JavaScript" : 0,
  "JSON" : 0,
  "Jupyter Notebook" : 0,
  "Kotlin" : 0,
  "Latte" : 0,
  "Less" : 0,
  "LiveScript" : 0,
  "LLVM" : 0,
  "Lua" : 0,
  "Mathematica" : 0,
  "Makefile" : 0,
  "Markdown" : 0,
  "Mask" : 0,
  "MATLAB" : 0,
  "Nginx" : 0,
  "OCaml" : 0,
  "Other" : 0,
  "Pascal" : 0,
  "Perl" : 0,
  "PHP" : 0,
  "PostCSS" : 0,
  "PowerShell" : 0,
  "Prisma" : 0,
  "Processing" : 0,
  "Python" : 0,
  "R" : 0,
  "React" : 0,
  "Regular Expression" : 0,
  "Ruby" : 0,
  "Rust" : 0,
  "Sass" : 0,
  "SAS" : 0,
  "Scala" : 0,
  "Scilab" : 0,
  "SCSS" : 0,
  "Shell" : 0,
  "SQL" : 0,
  "Svelte" : 0,
  "SVG" : 0,
  "Swift" : 0,
  "Text" : 0,
  "TypeScript" : 0,
  "Vim Script" : 0,
  "Visual Basic .NET" : 0,
  "Vue" : 0,
  "WebAssembly" : 0,
  "XML" : 0,
  "YAML" : 0,
}